services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./backend:/app
#      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run migration:run && npm run seed && npm run start:dev"

  db:
    image: mysql:8
#  volumes:
#    - ./mysql_db:/var/lib/mysql
#
    environment:
      - MYSQL_DATABASE=crm-programming-school
      - MYSQL_ROOT_PASSWORD=rootroot
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootroot"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

#  seed:
#    build:
#      context: .
#    env_file:
#      - .env
#    depends_on:
#      app:
#        condition: service_started
#    command: npm run seed

  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
